import os
import sys
	
direct = "gen/"

infiles = [
    "default.vert",
    "default.frag"
]

header = "shaders.h"

warning = "\n /*\n  *    ==== DO NOT EDIT THIS FILE ====\n  */\n\n"



curr = os.sep.join(sys.argv[0].split(os.sep)[:-1])+'/'

if not os.path.exists(curr+direct):
    os.mkdir(curr+direct)

header = direct + header

#if os.path.exists(header):
#    os.remove(header)


with open(curr+header, 'w') as fout:
    fout.write(warning)
    fout.write("#ifndef SHADERS_H\n#define SHADERS_H\n")

for fname in infiles:
    with open(curr+fname, 'r') as fin, open(curr+direct+fname+'.c', 'w') as fout:
        fout.write(warning)
        fout.write('const char ' + fname.replace('.', '_') + '[]=')
        for line in fin:
            nline = line.strip().replace('"', '\\"').replace('\\', '\\\\')
            if nline != "" and nline[0:2] != "//":
                fout.write('"'+nline+'\\n"\n')
        fout.write(';\n')
    
    with open(curr+header, 'a') as fout:
        fout.write('extern const char ' + fname.replace('.', '_') + '[];\n')


with open(curr+header, 'a') as fout:
    fout.write("#endif\n")
